In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("train.csv")
df.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Aaradhya,Female,49.0,Ludhiana,Working Professional,Chef,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Vivan,Male,26.0,Varanasi,Working Professional,Teacher,NaN,4.0,NaN,NaN,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Yuvraj,Male,33.0,Visakhapatnam,Student,NaN,5.0,NaN,8.97,2.0,NaN,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Yuvraj,Male,22.0,Mumbai,Working Professional,Teacher,NaN,5.0,NaN,NaN,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Rhea,Female,30.0,Kanpur,Working Professional,Business Analyst,NaN,1.0,NaN,NaN,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140700 entries, 0 to 140699
Data columns (total 20 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   id                                     140700 non-null  int64
 1   Name                                   140700 non-null  object
 2   Gender                                 140700 non-null  object
 3   Age                                    140700 non-null  float64
 4   City                                   140700 non-null  object
 5   Working Professional or Student        140700 non-null  object
 6   Profession                             104070 non-null  object
 7   Academic Pressure                      27897 non-null   float64
 8   Work Pressure                          112782 non-null  float64
 9   CGPA                                   27898 non-null   float64
 10  Study Satisfaction                     27897 non-null   float64
 11  Job Satisfaction                       112790 non-null  float64
 12  Sleep Duration                         140700 non-null  object
 13  Dietary Habits                         140696 non-null  object
 14  Degree                                 140698 non-null  object
 15  Have you ever had suicidal thoughts ?  140700 non-null  object
 16  Work/Study Hours                       140700 non-null  float64
 17  Financial Stress                       140696 non-null  float64
 18  Family History of Mental Illness       140700 non-null  object
 19  Depression                             140700 non-null  int64
dtypes: float64(8), int64(2), object(10)
memory usage: 21.5+ MB

In [4]:
for i in df.columns:
    if df[i].isna().sum()!=0:
        print(i,df[i].isna().sum())

Profession 36630
Academic Pressure 112803
Work Pressure 27918
CGPA 112802
Study Satisfaction 112803
Job Satisfaction 27910
Dietary Habits 4
Degree 2
Financial Stress 4

I will split the dataset into a student dataset and a professional dataset. So then I don't have to drop as many rows. I will also drop or maybe even impute the values of the columns missing less than 10 values

In [63]:
df_student = df.loc[df['Working Professional or Student'] == "Student"]
for i in df_student.columns:
    if df_student[i].isna().sum()!=0:
        print(i,df_student[i].isna().sum())

Profession 27867
Academic Pressure 9
Work Pressure 27898
CGPA 9
Study Satisfaction 10
Job Satisfaction 27893
Dietary Habits 2
Financial Stress 3

In [64]:
del df_student["Profession"]
del df_student["Work Pressure"]
del df_student["Job Satisfaction"]
del df_student["Name"]
del df_student["id"]
del df_student["Working Professional or Student"]

In [65]:
for i in df_student.columns:
    if df_student[i].isna().sum()!=0:
        print(i,df_student[i].isna().sum())

Academic Pressure 9
CGPA 9
Study Satisfaction 10
Dietary Habits 2
Financial Stress 3

In [67]:
for i in df_student.columns:
    if df_student[i].dtype=="object":
        print(i)

Gender
City
Sleep Duration
Dietary Habits
Degree
Have you ever had suicidal thoughts ?
Family History of Mental Illness

In [68]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [69]:
enc = LabelEncoder()
enc.fit(df_student.Gender.unique())
df_student.Gender = enc.transform(df_student.Gender)
enc = LabelEncoder()
enc.fit(df_student.City.unique())
df_student.City = enc.transform(df_student.City)
enc = LabelEncoder()
enc.fit(df_student["Sleep Duration"].unique())
df_student["Sleep Duration"] = enc.transform(df_student["Sleep Duration"])
enc = LabelEncoder()
enc.fit(df_student["Dietary Habits"].unique())
df_student["Dietary Habits"] = enc.transform(df_student["Dietary Habits"])
enc = LabelEncoder()
enc.fit(df_student["Degree"].unique())
df_student["Degree"] = enc.transform(df_student["Degree"])
enc = LabelEncoder()
enc.fit(df_student["Have you ever had suicidal thoughts ?"].unique())
df_student["Have you ever had suicidal thoughts ?"] = enc.transform(df_student["Have you ever had suicidal thoughts ?"])
enc = LabelEncoder()
enc.fit(df_student["Family History of Mental Illness"].unique())
df_student["Family History of Mental Illness"] = enc.transform(df_student["Family History of Mental Illness"])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student.Gender = enc.transform(df_student.Gender)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student.City = enc.transform(df_student.City)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student["Sleep Duration"] = enc.transform(df_student["Sleep Duration"])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student["Dietary Habits"] = enc.transform(df_student["Dietary Habits"])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student["Degree"] = enc.transform(df_student["Degree"])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student["Have you ever had suicidal thoughts ?"] = enc.transform(df_student["Have you ever had suicidal thoughts ?"])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\997860755.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student["Family History of Mental Illness"] = enc.transform(df_student["Family History of Mental Illness"])

In [70]:
for i in df_student.columns:
    if df_student[i].dtype=="object":
        print(i)

In [71]:
df_student[:] = SimpleImputer(missing_values=np.nan, strategy='median').fit_transform(df_student)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19236\113033607.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_student[:] = SimpleImputer(missing_values=np.nan, strategy='median').fit_transform(df_student)

In [73]:
for i in df_student.columns:
    if df_student[i].isna().sum()!=0:
        print(i,df_student[i].isna().sum())

In [74]:
df_student.head()

,Gender,Age,City,Academic Pressure,CGPA,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
2,1,33.0,51,5.0,8.97,2.0,7,3,9,1,3.0,1.0,0,1
8,0,24.0,3,2.0,5.90,5.0,7,9,22,0,3.0,2.0,1,0
26,1,31.0,44,3.0,7.03,5.0,12,3,13,0,9.0,1.0,1,0
30,0,28.0,49,3.0,5.59,2.0,10,9,16,1,4.0,5.0,1,1
32,0,25.0,16,4.0,8.13,3.0,7,9,44,1,1.0,1.0,0,0